"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.sRgbToEciRgbV2 = exports.sRgbToDonRgb4 = exports.sRgbToColorMatchRgb = exports.sRgbToCmyk = exports.sRgbToCmy = exports.sRgbToCieRgb = exports.sRgbToBruceRgb = exports.sRgbToBetaRgb = exports.sRgbToBestRgb = exports.sRgbToAppleRgb = exports.sRgbToAnsi256 = exports.sRgbToAnsi16 = exports.sRgbToAdobeRgb = exports.rgbInvert = exports.deNormalizeRGB = exports.normalizeRgba = exports.normalizeRgb = exports.numberToRGB = exports.luvToXyz = exports.luvToLch_uv = exports.lmsToXyz = exports.lch_uvToXyz = exports.lch_uvToLuv = exports.lch_abToXyz = exports.lch_abToLab = exports.labToXyz = exports.labToSrgb = exports.labToLch_ab = exports.hwbToRgb = exports.hueToRGB = exports.hsvToRgb = exports.hsvToHsl = exports.hsvToAnsi16 = exports.hslToRgb = exports.hslToHsv = exports.hslToHex = exports.hsiToSrgb = exports.hexToRgb = exports.hexToInt = exports.hexToDecimal = exports.hcyToSrgb = exports.hclToLab = exports.cmykToRgb = exports.cmyToSRgb = exports.ansi256ToRgb = exports.ansi16ToRgb = exports.ansi16ToAnsi8 = exports.Color = exports.RgbConverter = exports.XyzConverter = void 0;
exports.xvYccToSrgb = exports.uvwToXyz = exports.tslToSrgb = exports.rybToSrgb = exports.eciRgbV2ToXyz = exports.wideGamutRgbToXyz = exports.smpteCRgbToXyz = exports.proPhotoRgbToXyz = exports.palSecamRgbToXyz = exports.ntscRgbToXyz = exports.etkaSpacePs5ToXyz = exports.donRgb4ToXyz = exports.colorMatchRgbToXyz = exports.cieRgbToXyz = exports.bruceRgbToXyz = exports.betaRgbToXyz = exports.bestRgbToXyz = exports.appleRgbToXyz = exports.adobeRgbToXyz = exports.sRgbaToHex = exports.sRgbToYiq = exports.sRgbToYcCbcCrc = exports.sRgbToYPbPr = exports.sRgbToYDbDr = exports.sRgbToYCgCo = exports.sRgbToYCbCrBT709 = exports.sRgbToYCbCrBT601 = exports.sRgbToXyz = exports.sRgbToXvYcc = exports.sRgbToWideGamutRgb = exports.sRgbToUvw = exports.sRgbToTsl = exports.sRgbToSmpteCRgb = exports.sRgbToRyb = exports.sRgbToProPhotoRgb = exports.sRgbToPalSecamRgb = exports.sRgbToNtscRgb = exports.sRgbToLuv = exports.sRgbToLuminance = exports.sRgbToLch_uv = exports.sRgbToLch_ab = exports.sRgbToLab = exports.sRgbToHwb = exports.sRgbToHue = exports.sRgbToHsv = exports.sRgbToHsl = exports.sRgbToHsi = exports.sRgbToHex = exports.sRgbToHcy = exports.sRgbToEtkaSpacePs5 = void 0;
exports.AtoF11Adaptation = exports.AtoF7Adaptation = exports.AtoF2Adaptation = exports.AtoEAdaptation = exports.AtoD75Adaptation = exports.AtoD65Adaptation = exports.AtoD55Adaptation = exports.AtoD50Adaptation = exports.AtoCAdaptation = exports.AtoBAdaptation = exports.chromaticAdaptationPreCal = exports.bradfordChromaticAdaptation = exports.yPbPrToYCbCr = exports.yPbPrToSrgb = exports.yiqToSrgb = exports.yDbDrToSrgb = exports.yCgCoToSrgb = exports.ycCbcCrcToSrgb = exports.yCbCrBT709ToSrgb = exports.yCbCrBT601ToYPbPr = exports.yCbCrBT601ToXvYcc = exports.yCbCrBT601ToSrgb = exports.xyzToLms = exports.xyzToXyY = exports.xyzToWideGamutRgb = exports.xyzToUvw = exports.xyzToSmpteCRgb = exports.xyzToProPhotoRgb = exports.xyzToPalSecamRgb = exports.xyzToNtscRgb = exports.xyzToSrgb = exports.xyzToLRgb = exports.xyzToLuv = exports.xyzToLch_uv = exports.xyzToLch_ab = exports.xyzToLab = exports.xyzToHunterLab = exports.xyzToGammaRgb = exports.xyzToEtkaSpacePs5 = exports.xyzToEciRgbV2 = exports.xyzToDonRgb4 = exports.xyzToColorMatchRgb = exports.xyzToCieRgb = exports.xyzToBruceRgb = exports.xyzToBetaRgb = exports.xyzToBestRgb = exports.xyzToAppleRgb = exports.xyzToAdobeRgb = exports.xyYToXyz = exports.xvYccToYcbcrBT601 = void 0;
exports.D65toF11Adaptation = exports.D65toF7Adaptation = exports.D65toF2Adaptation = exports.D65toEAdaptation = exports.D65toD75Adaptation = exports.D65toD55Adaptation = exports.D65toD50Adaptation = exports.D65toCAdaptation = exports.D65toBAdaptation = exports.D65toAAdaptation = exports.D55toF11Adaptation = exports.D55toF7Adaptation = exports.D55toF2Adaptation = exports.D55toEAdaptation = exports.D55toD75Adaptation = exports.D55toD65Adaptation = exports.D55toD50Adaptation = exports.D55toCAdaptation = exports.D55toBAdaptation = exports.D55toAAdaptation = exports.D50toF11Adaptation = exports.D50toF7Adaptation = exports.D50toF2Adaptation = exports.D50toEAdaptation = exports.D50toD75Adaptation = exports.D50toD65Adaptation = exports.D50toD55Adaptation = exports.D50toCAdaptation = exports.D50toBAdaptation = exports.D50toAAdaptation = exports.CtoF11Adaptation = exports.CtoF7Adaptation = exports.CtoF2Adaptation = exports.CtoEAdaptation = exports.CtoD75Adaptation = exports.CtoD65Adaptation = exports.CtoD55Adaptation = exports.CtoD50Adaptation = exports.CtoBAdaptation = exports.CtoAAdaptation = exports.BtoF11Adaptation = exports.BtoF7Adaptation = exports.BtoF2Adaptation = exports.BtoEAdaptation = exports.BtoD75Adaptation = exports.BtoD65Adaptation = exports.BtoD55Adaptation = exports.BtoD50Adaptation = exports.BtoCAdaptation = exports.BtoAAdaptation = void 0;
exports.F11toF7Adaptation = exports.F11toF2Adaptation = exports.F11toEAdaptation = exports.F11toD75Adaptation = exports.F11ToD65Adaptation = exports.F11toD55Adaptation = exports.F11toD50Adaptation = exports.F11toCAdaptation = exports.F11toBAdaptation = exports.F11toAAdaptation = exports.F7toF11Adaptation = exports.F7toF2Adaptation = exports.F7toEAdaptation = exports.F7toD75Adaptation = exports.F7ToD65Adaptation = exports.F7toD55Adaptation = exports.F7toD50Adaptation = exports.F7toCAdaptation = exports.F7toBAdaptation = exports.F7toAAdaptation = exports.F2toF11Adaptation = exports.F2toF7Adaptation = exports.F2toEAdaptation = exports.F2toD75Adaptation = exports.F2toD65Adaptation = exports.F2toD55Adaptation = exports.F2toD50Adaptation = exports.F2toCAdaptation = exports.F2toBAdaptation = exports.F2toAAdaptation = exports.EtoF11Adaptation = exports.EtoF7Adaptation = exports.EtoF2Adaptation = exports.EtoD75Adaptation = exports.EtoD65Adaptation = exports.EtoD55Adaptation = exports.EtoD50Adaptation = exports.EtoCAdaptation = exports.EtoBAdaptation = exports.EtoAAdaptation = exports.D75toF11Adaptation = exports.D75toF7Adaptation = exports.D75toF2Adaptation = exports.D75toEAdaptation = exports.D75toD65Adaptation = exports.D75toD55Adaptation = exports.D75toD50Adaptation = exports.D75toCAdaptation = exports.D75toBAdaptation = exports.D75toAAdaptation = void 0;
exports.deltaECIE94Lab = exports.deltaECIE76Rgb = exports.deltaECIE76Lch = exports.deltaECIE76Lab = exports.deltaECIE00Rgb = exports.deltaECIE00Lab = exports.Adapter = exports.adapt = exports.getTones = exports.getTints = exports.getShades = exports.squareHarmony = exports.analogousHarmony = exports.neutralHarmony = exports.sixToneCCWHarmony = exports.sixToneCWHarmony = exports.fiveToneEHarmony = exports.fiveToneDHarmony = exports.fiveToneCHarmony = exports.fiveToneBHarmony = exports.fiveToneAHarmony = exports.fourToneCCWHarmony = exports.fourToneCWHarmony = exports.tetradicHarmony = exports.triadicHarmony = exports.splitComplementaryCCWHarmony = exports.splitComplementaryCWHarmony = exports.splitComplementaryHarmony = exports.complementaryHarmony = exports.Blender = exports.blend = void 0;
var xyz_converter_1 = require("./color-converter/xyz-converter");
Object.defineProperty(exports, "XyzConverter", { enumerable: true, get: function () { return xyz_converter_1.XyzConverter; } });
var rgb_converter_1 = require("./color-converter/rgb-converter");
Object.defineProperty(exports, "RgbConverter", { enumerable: true, get: function () { return rgb_converter_1.RgbConverter; } });
var color_1 = require("./color/color");
Object.defineProperty(exports, "Color", { enumerable: true, get: function () { return color_1.Color; } });
var ansi_conversions_1 = require("./conversions/ansi-conversions");
Object.defineProperty(exports, "ansi16ToAnsi8", { enumerable: true, get: function () { return ansi_conversions_1.ansi16ToAnsi8; } });
Object.defineProperty(exports, "ansi16ToRgb", { enumerable: true, get: function () { return ansi_conversions_1.ansi16ToRgb; } });
Object.defineProperty(exports, "ansi256ToRgb", { enumerable: true, get: function () { return ansi_conversions_1.ansi256ToRgb; } });
var cmy_conversions_1 = require("./conversions/cmy-conversions");
Object.defineProperty(exports, "cmyToSRgb", { enumerable: true, get: function () { return cmy_conversions_1.cmyToSRgb; } });
var cmyk_conversions_1 = require("./conversions/cmyk-conversions");
Object.defineProperty(exports, "cmykToRgb", { enumerable: true, get: function () { return cmyk_conversions_1.cmykToRgb; } });
var hcl_conversions_1 = require("./conversions/hcl-conversions");
Object.defineProperty(exports, "hclToLab", { enumerable: true, get: function () { return hcl_conversions_1.hclToLab; } });
var hcy_conversions_1 = require("./conversions/hcy-conversions");
Object.defineProperty(exports, "hcyToSrgb", { enumerable: true, get: function () { return hcy_conversions_1.hcyToSrgb; } });
var hex_conversions_1 = require("./conversions/hex-conversions");
Object.defineProperty(exports, "hexToDecimal", { enumerable: true, get: function () { return hex_conversions_1.hexToDecimal; } });
Object.defineProperty(exports, "hexToInt", { enumerable: true, get: function () { return hex_conversions_1.hexToInt; } });
Object.defineProperty(exports, "hexToRgb", { enumerable: true, get: function () { return hex_conversions_1.hexToRgb; } });
var hsi_conversions_1 = require("./conversions/hsi-conversions");
Object.defineProperty(exports, "hsiToSrgb", { enumerable: true, get: function () { return hsi_conversions_1.hsiToSrgb; } });
var hsl_conversions_1 = require("./conversions/hsl-conversions");
Object.defineProperty(exports, "hslToHex", { enumerable: true, get: function () { return hsl_conversions_1.hslToHex; } });
Object.defineProperty(exports, "hslToHsv", { enumerable: true, get: function () { return hsl_conversions_1.hslToHsv; } });
Object.defineProperty(exports, "hslToRgb", { enumerable: true, get: function () { return hsl_conversions_1.hslToRgb; } });
var hsv_conversions_1 = require("./conversions/hsv-conversions");
Object.defineProperty(exports, "hsvToAnsi16", { enumerable: true, get: function () { return hsv_conversions_1.hsvToAnsi16; } });
Object.defineProperty(exports, "hsvToHsl", { enumerable: true, get: function () { return hsv_conversions_1.hsvToHsl; } });
Object.defineProperty(exports, "hsvToRgb", { enumerable: true, get: function () { return hsv_conversions_1.hsvToRgb; } });
var hue_conversions_1 = require("./conversions/hue-conversions");
Object.defineProperty(exports, "hueToRGB", { enumerable: true, get: function () { return hue_conversions_1.hueToRGB; } });
var hwb_conversions_1 = require("./conversions/hwb-conversions");
Object.defineProperty(exports, "hwbToRgb", { enumerable: true, get: function () { return hwb_conversions_1.hwbToRgb; } });
var lab_conversions_1 = require("./conversions/lab-conversions");
Object.defineProperty(exports, "labToLch_ab", { enumerable: true, get: function () { return lab_conversions_1.labToLch_ab; } });
Object.defineProperty(exports, "labToSrgb", { enumerable: true, get: function () { return lab_conversions_1.labToSrgb; } });
Object.defineProperty(exports, "labToXyz", { enumerable: true, get: function () { return lab_conversions_1.labToXyz; } });
var lch_conversions_1 = require("./conversions/lch-conversions");
Object.defineProperty(exports, "lch_abToLab", { enumerable: true, get: function () { return lch_conversions_1.lch_abToLab; } });
Object.defineProperty(exports, "lch_abToXyz", { enumerable: true, get: function () { return lch_conversions_1.lch_abToXyz; } });
Object.defineProperty(exports, "lch_uvToLuv", { enumerable: true, get: function () { return lch_conversions_1.lch_uvToLuv; } });
Object.defineProperty(exports, "lch_uvToXyz", { enumerable: true, get: function () { return lch_conversions_1.lch_uvToXyz; } });
var lms_conversions_1 = require("./conversions/lms-conversions");
Object.defineProperty(exports, "lmsToXyz", { enumerable: true, get: function () { return lms_conversions_1.lmsToXyz; } });
var luv_conversions_1 = require("./conversions/luv-conversions");
Object.defineProperty(exports, "luvToLch_uv", { enumerable: true, get: function () { return luv_conversions_1.luvToLch_uv; } });
Object.defineProperty(exports, "luvToXyz", { enumerable: true, get: function () { return luv_conversions_1.luvToXyz; } });
var number_conversions_1 = require("./conversions/number-conversions");
Object.defineProperty(exports, "numberToRGB", { enumerable: true, get: function () { return number_conversions_1.numberToRGB; } });
var rgb_conversions_1 = require("./conversions/rgb-conversions");
Object.defineProperty(exports, "normalizeRgb", { enumerable: true, get: function () { return rgb_conversions_1.normalizeRgb; } });
Object.defineProperty(exports, "normalizeRgba", { enumerable: true, get: function () { return rgb_conversions_1.normalizeRgba; } });
Object.defineProperty(exports, "deNormalizeRGB", { enumerable: true, get: function () { return rgb_conversions_1.deNormalizeRGB; } });
Object.defineProperty(exports, "rgbInvert", { enumerable: true, get: function () { return rgb_conversions_1.rgbInvert; } });
Object.defineProperty(exports, "sRgbToAdobeRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToAdobeRgb; } });
Object.defineProperty(exports, "sRgbToAnsi16", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToAnsi16; } });
Object.defineProperty(exports, "sRgbToAnsi256", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToAnsi256; } });
Object.defineProperty(exports, "sRgbToAppleRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToAppleRgb; } });
Object.defineProperty(exports, "sRgbToBestRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToBestRgb; } });
Object.defineProperty(exports, "sRgbToBetaRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToBetaRgb; } });
Object.defineProperty(exports, "sRgbToBruceRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToBruceRgb; } });
Object.defineProperty(exports, "sRgbToCieRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToCieRgb; } });
Object.defineProperty(exports, "sRgbToCmy", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToCmy; } });
Object.defineProperty(exports, "sRgbToCmyk", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToCmyk; } });
Object.defineProperty(exports, "sRgbToColorMatchRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToColorMatchRgb; } });
Object.defineProperty(exports, "sRgbToDonRgb4", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToDonRgb4; } });
Object.defineProperty(exports, "sRgbToEciRgbV2", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToEciRgbV2; } });
Object.defineProperty(exports, "sRgbToEtkaSpacePs5", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToEtkaSpacePs5; } });
Object.defineProperty(exports, "sRgbToHcy", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHcy; } });
Object.defineProperty(exports, "sRgbToHex", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHex; } });
Object.defineProperty(exports, "sRgbToHsi", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHsi; } });
Object.defineProperty(exports, "sRgbToHsl", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHsl; } });
Object.defineProperty(exports, "sRgbToHsv", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHsv; } });
Object.defineProperty(exports, "sRgbToHue", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHue; } });
Object.defineProperty(exports, "sRgbToHwb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToHwb; } });
Object.defineProperty(exports, "sRgbToLab", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToLab; } });
Object.defineProperty(exports, "sRgbToLch_ab", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToLch_ab; } });
Object.defineProperty(exports, "sRgbToLch_uv", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToLch_uv; } });
Object.defineProperty(exports, "sRgbToLuminance", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToLuminance; } });
Object.defineProperty(exports, "sRgbToLuv", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToLuv; } });
Object.defineProperty(exports, "sRgbToNtscRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToNtscRgb; } });
Object.defineProperty(exports, "sRgbToPalSecamRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToPalSecamRgb; } });
Object.defineProperty(exports, "sRgbToProPhotoRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToProPhotoRgb; } });
Object.defineProperty(exports, "sRgbToRyb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToRyb; } });
Object.defineProperty(exports, "sRgbToSmpteCRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToSmpteCRgb; } });
Object.defineProperty(exports, "sRgbToTsl", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToTsl; } });
Object.defineProperty(exports, "sRgbToUvw", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToUvw; } });
Object.defineProperty(exports, "sRgbToWideGamutRgb", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToWideGamutRgb; } });
Object.defineProperty(exports, "sRgbToXvYcc", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToXvYcc; } });
Object.defineProperty(exports, "sRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToXyz; } });
Object.defineProperty(exports, "sRgbToYCbCrBT601", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYCbCrBT601; } });
Object.defineProperty(exports, "sRgbToYCbCrBT709", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYCbCrBT709; } });
Object.defineProperty(exports, "sRgbToYCgCo", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYCgCo; } });
Object.defineProperty(exports, "sRgbToYDbDr", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYDbDr; } });
Object.defineProperty(exports, "sRgbToYPbPr", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYPbPr; } });
Object.defineProperty(exports, "sRgbToYcCbcCrc", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYcCbcCrc; } });
Object.defineProperty(exports, "sRgbToYiq", { enumerable: true, get: function () { return rgb_conversions_1.sRgbToYiq; } });
Object.defineProperty(exports, "sRgbaToHex", { enumerable: true, get: function () { return rgb_conversions_1.sRgbaToHex; } });
Object.defineProperty(exports, "adobeRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.adobeRgbToXyz; } });
Object.defineProperty(exports, "appleRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.appleRgbToXyz; } });
Object.defineProperty(exports, "bestRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.bestRgbToXyz; } });
Object.defineProperty(exports, "betaRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.betaRgbToXyz; } });
Object.defineProperty(exports, "bruceRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.bruceRgbToXyz; } });
Object.defineProperty(exports, "cieRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.cieRgbToXyz; } });
Object.defineProperty(exports, "colorMatchRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.colorMatchRgbToXyz; } });
Object.defineProperty(exports, "donRgb4ToXyz", { enumerable: true, get: function () { return rgb_conversions_1.donRgb4ToXyz; } });
Object.defineProperty(exports, "etkaSpacePs5ToXyz", { enumerable: true, get: function () { return rgb_conversions_1.etkaSpacePs5ToXyz; } });
Object.defineProperty(exports, "ntscRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.ntscRgbToXyz; } });
Object.defineProperty(exports, "palSecamRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.palSecamRgbToXyz; } });
Object.defineProperty(exports, "proPhotoRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.proPhotoRgbToXyz; } });
Object.defineProperty(exports, "smpteCRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.smpteCRgbToXyz; } });
Object.defineProperty(exports, "wideGamutRgbToXyz", { enumerable: true, get: function () { return rgb_conversions_1.wideGamutRgbToXyz; } });
Object.defineProperty(exports, "eciRgbV2ToXyz", { enumerable: true, get: function () { return rgb_conversions_1.eciRgbV2ToXyz; } });
var ryb_conversions_1 = require("./conversions/ryb-conversions");
Object.defineProperty(exports, "rybToSrgb", { enumerable: true, get: function () { return ryb_conversions_1.rybToSrgb; } });
var tsl_conversions_1 = require("./conversions/tsl-conversions");
Object.defineProperty(exports, "tslToSrgb", { enumerable: true, get: function () { return tsl_conversions_1.tslToSrgb; } });
var uvw_conversions_1 = require("./conversions/uvw-conversions");
Object.defineProperty(exports, "uvwToXyz", { enumerable: true, get: function () { return uvw_conversions_1.uvwToXyz; } });
var xvycc_conversions_1 = require("./conversions/xvycc-conversions");
Object.defineProperty(exports, "xvYccToSrgb", { enumerable: true, get: function () { return xvycc_conversions_1.xvYccToSrgb; } });
Object.defineProperty(exports, "xvYccToYcbcrBT601", { enumerable: true, get: function () { return xvycc_conversions_1.xvYccToYcbcrBT601; } });
var xyy_conversions_1 = require("./conversions/xyy-conversions");
Object.defineProperty(exports, "xyYToXyz", { enumerable: true, get: function () { return xyy_conversions_1.xyYToXyz; } });
var xyz_conversions_1 = require("./conversions/xyz-conversions");
Object.defineProperty(exports, "xyzToAdobeRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToAdobeRgb; } });
Object.defineProperty(exports, "xyzToAppleRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToAppleRgb; } });
Object.defineProperty(exports, "xyzToBestRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToBestRgb; } });
Object.defineProperty(exports, "xyzToBetaRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToBetaRgb; } });
Object.defineProperty(exports, "xyzToBruceRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToBruceRgb; } });
Object.defineProperty(exports, "xyzToCieRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToCieRgb; } });
Object.defineProperty(exports, "xyzToColorMatchRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToColorMatchRgb; } });
Object.defineProperty(exports, "xyzToDonRgb4", { enumerable: true, get: function () { return xyz_conversions_1.xyzToDonRgb4; } });
Object.defineProperty(exports, "xyzToEciRgbV2", { enumerable: true, get: function () { return xyz_conversions_1.xyzToEciRgbV2; } });
Object.defineProperty(exports, "xyzToEtkaSpacePs5", { enumerable: true, get: function () { return xyz_conversions_1.xyzToEtkaSpacePs5; } });
Object.defineProperty(exports, "xyzToGammaRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToGammaRgb; } });
Object.defineProperty(exports, "xyzToHunterLab", { enumerable: true, get: function () { return xyz_conversions_1.xyzToHunterLab; } });
Object.defineProperty(exports, "xyzToLab", { enumerable: true, get: function () { return xyz_conversions_1.xyzToLab; } });
Object.defineProperty(exports, "xyzToLch_ab", { enumerable: true, get: function () { return xyz_conversions_1.xyzToLch_ab; } });
Object.defineProperty(exports, "xyzToLch_uv", { enumerable: true, get: function () { return xyz_conversions_1.xyzToLch_uv; } });
Object.defineProperty(exports, "xyzToLuv", { enumerable: true, get: function () { return xyz_conversions_1.xyzToLuv; } });
Object.defineProperty(exports, "xyzToLRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToLRgb; } });
Object.defineProperty(exports, "xyzToSrgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToSrgb; } });
Object.defineProperty(exports, "xyzToNtscRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToNtscRgb; } });
Object.defineProperty(exports, "xyzToPalSecamRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToPalSecamRgb; } });
Object.defineProperty(exports, "xyzToProPhotoRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToProPhotoRgb; } });
Object.defineProperty(exports, "xyzToSmpteCRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToSmpteCRgb; } });
Object.defineProperty(exports, "xyzToUvw", { enumerable: true, get: function () { return xyz_conversions_1.xyzToUvw; } });
Object.defineProperty(exports, "xyzToWideGamutRgb", { enumerable: true, get: function () { return xyz_conversions_1.xyzToWideGamutRgb; } });
Object.defineProperty(exports, "xyzToXyY", { enumerable: true, get: function () { return xyz_conversions_1.xyzToXyY; } });
Object.defineProperty(exports, "xyzToLms", { enumerable: true, get: function () { return xyz_conversions_1.xyzToLms; } });
var ycbcr_jpeg_conversions_1 = require("./conversions/ycbcr-jpeg-conversions");
Object.defineProperty(exports, "yCbCrBT601ToSrgb", { enumerable: true, get: function () { return ycbcr_jpeg_conversions_1.yCbCrBT601ToSrgb; } });
Object.defineProperty(exports, "yCbCrBT601ToXvYcc", { enumerable: true, get: function () { return ycbcr_jpeg_conversions_1.yCbCrBT601ToXvYcc; } });
Object.defineProperty(exports, "yCbCrBT601ToYPbPr", { enumerable: true, get: function () { return ycbcr_jpeg_conversions_1.yCbCrBT601ToYPbPr; } });
Object.defineProperty(exports, "yCbCrBT709ToSrgb", { enumerable: true, get: function () { return ycbcr_jpeg_conversions_1.yCbCrBT709ToSrgb; } });
var yccbccrc_conversions_1 = require("./conversions/yccbccrc-conversions");
Object.defineProperty(exports, "ycCbcCrcToSrgb", { enumerable: true, get: function () { return yccbccrc_conversions_1.ycCbcCrcToSrgb; } });
var ycocg_conversions_1 = require("./conversions/ycocg-conversions");
Object.defineProperty(exports, "yCgCoToSrgb", { enumerable: true, get: function () { return ycocg_conversions_1.yCgCoToSrgb; } });
var ydbdr_conversions_1 = require("./conversions/ydbdr-conversions");
Object.defineProperty(exports, "yDbDrToSrgb", { enumerable: true, get: function () { return ydbdr_conversions_1.yDbDrToSrgb; } });
var yiq_conversions_1 = require("./conversions/yiq-conversions");
Object.defineProperty(exports, "yiqToSrgb", { enumerable: true, get: function () { return yiq_conversions_1.yiqToSrgb; } });
var ypbpr_conversions_1 = require("./conversions/ypbpr-conversions");
Object.defineProperty(exports, "yPbPrToSrgb", { enumerable: true, get: function () { return ypbpr_conversions_1.yPbPrToSrgb; } });
Object.defineProperty(exports, "yPbPrToYCbCr", { enumerable: true, get: function () { return ypbpr_conversions_1.yPbPrToYCbCr; } });
var chromatic_adaptation_1 = require("./helpers/chromatic-adaptation");
Object.defineProperty(exports, "bradfordChromaticAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.bradfordChromaticAdaptation; } });
Object.defineProperty(exports, "chromaticAdaptationPreCal", { enumerable: true, get: function () { return chromatic_adaptation_1.chromaticAdaptationPreCal; } });
Object.defineProperty(exports, "AtoBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoBAdaptation; } });
Object.defineProperty(exports, "AtoCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoCAdaptation; } });
Object.defineProperty(exports, "AtoD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoD50Adaptation; } });
Object.defineProperty(exports, "AtoD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoD55Adaptation; } });
Object.defineProperty(exports, "AtoD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoD65Adaptation; } });
Object.defineProperty(exports, "AtoD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoD75Adaptation; } });
Object.defineProperty(exports, "AtoEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoEAdaptation; } });
Object.defineProperty(exports, "AtoF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoF2Adaptation; } });
Object.defineProperty(exports, "AtoF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoF7Adaptation; } });
Object.defineProperty(exports, "AtoF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.AtoF11Adaptation; } });
Object.defineProperty(exports, "BtoAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoAAdaptation; } });
Object.defineProperty(exports, "BtoCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoCAdaptation; } });
Object.defineProperty(exports, "BtoD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoD50Adaptation; } });
Object.defineProperty(exports, "BtoD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoD55Adaptation; } });
Object.defineProperty(exports, "BtoD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoD65Adaptation; } });
Object.defineProperty(exports, "BtoD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoD75Adaptation; } });
Object.defineProperty(exports, "BtoEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoEAdaptation; } });
Object.defineProperty(exports, "BtoF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoF2Adaptation; } });
Object.defineProperty(exports, "BtoF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoF7Adaptation; } });
Object.defineProperty(exports, "BtoF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.BtoF11Adaptation; } });
Object.defineProperty(exports, "CtoAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoAAdaptation; } });
Object.defineProperty(exports, "CtoBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoBAdaptation; } });
Object.defineProperty(exports, "CtoD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoD50Adaptation; } });
Object.defineProperty(exports, "CtoD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoD55Adaptation; } });
Object.defineProperty(exports, "CtoD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoD65Adaptation; } });
Object.defineProperty(exports, "CtoD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoD75Adaptation; } });
Object.defineProperty(exports, "CtoEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoEAdaptation; } });
Object.defineProperty(exports, "CtoF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoF2Adaptation; } });
Object.defineProperty(exports, "CtoF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoF7Adaptation; } });
Object.defineProperty(exports, "CtoF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.CtoF11Adaptation; } });
Object.defineProperty(exports, "D50toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toAAdaptation; } });
Object.defineProperty(exports, "D50toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toBAdaptation; } });
Object.defineProperty(exports, "D50toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toCAdaptation; } });
Object.defineProperty(exports, "D50toD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toD55Adaptation; } });
Object.defineProperty(exports, "D50toD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toD65Adaptation; } });
Object.defineProperty(exports, "D50toD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toD75Adaptation; } });
Object.defineProperty(exports, "D50toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toEAdaptation; } });
Object.defineProperty(exports, "D50toF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toF2Adaptation; } });
Object.defineProperty(exports, "D50toF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toF7Adaptation; } });
Object.defineProperty(exports, "D50toF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D50toF11Adaptation; } });
Object.defineProperty(exports, "D55toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toAAdaptation; } });
Object.defineProperty(exports, "D55toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toBAdaptation; } });
Object.defineProperty(exports, "D55toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toCAdaptation; } });
Object.defineProperty(exports, "D55toD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toD50Adaptation; } });
Object.defineProperty(exports, "D55toD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toD65Adaptation; } });
Object.defineProperty(exports, "D55toD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toD75Adaptation; } });
Object.defineProperty(exports, "D55toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toEAdaptation; } });
Object.defineProperty(exports, "D55toF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toF2Adaptation; } });
Object.defineProperty(exports, "D55toF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toF7Adaptation; } });
Object.defineProperty(exports, "D55toF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D55toF11Adaptation; } });
Object.defineProperty(exports, "D65toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toAAdaptation; } });
Object.defineProperty(exports, "D65toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toBAdaptation; } });
Object.defineProperty(exports, "D65toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toCAdaptation; } });
Object.defineProperty(exports, "D65toD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toD50Adaptation; } });
Object.defineProperty(exports, "D65toD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toD55Adaptation; } });
Object.defineProperty(exports, "D65toD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toD75Adaptation; } });
Object.defineProperty(exports, "D65toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toEAdaptation; } });
Object.defineProperty(exports, "D65toF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toF2Adaptation; } });
Object.defineProperty(exports, "D65toF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toF7Adaptation; } });
Object.defineProperty(exports, "D65toF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D65toF11Adaptation; } });
Object.defineProperty(exports, "D75toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toAAdaptation; } });
Object.defineProperty(exports, "D75toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toBAdaptation; } });
Object.defineProperty(exports, "D75toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toCAdaptation; } });
Object.defineProperty(exports, "D75toD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toD50Adaptation; } });
Object.defineProperty(exports, "D75toD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toD55Adaptation; } });
Object.defineProperty(exports, "D75toD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toD65Adaptation; } });
Object.defineProperty(exports, "D75toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toEAdaptation; } });
Object.defineProperty(exports, "D75toF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toF2Adaptation; } });
Object.defineProperty(exports, "D75toF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toF7Adaptation; } });
Object.defineProperty(exports, "D75toF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.D75toF11Adaptation; } });
Object.defineProperty(exports, "EtoAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoAAdaptation; } });
Object.defineProperty(exports, "EtoBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoBAdaptation; } });
Object.defineProperty(exports, "EtoCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoCAdaptation; } });
Object.defineProperty(exports, "EtoD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoD50Adaptation; } });
Object.defineProperty(exports, "EtoD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoD55Adaptation; } });
Object.defineProperty(exports, "EtoD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoD65Adaptation; } });
Object.defineProperty(exports, "EtoD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoD75Adaptation; } });
Object.defineProperty(exports, "EtoF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoF2Adaptation; } });
Object.defineProperty(exports, "EtoF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoF7Adaptation; } });
Object.defineProperty(exports, "EtoF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.EtoF11Adaptation; } });
Object.defineProperty(exports, "F2toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toAAdaptation; } });
Object.defineProperty(exports, "F2toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toBAdaptation; } });
Object.defineProperty(exports, "F2toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toCAdaptation; } });
Object.defineProperty(exports, "F2toD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toD50Adaptation; } });
Object.defineProperty(exports, "F2toD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toD55Adaptation; } });
Object.defineProperty(exports, "F2toD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toD65Adaptation; } });
Object.defineProperty(exports, "F2toD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toD75Adaptation; } });
Object.defineProperty(exports, "F2toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toEAdaptation; } });
Object.defineProperty(exports, "F2toF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toF7Adaptation; } });
Object.defineProperty(exports, "F2toF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F2toF11Adaptation; } });
Object.defineProperty(exports, "F7toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toAAdaptation; } });
Object.defineProperty(exports, "F7toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toBAdaptation; } });
Object.defineProperty(exports, "F7toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toCAdaptation; } });
Object.defineProperty(exports, "F7toD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toD50Adaptation; } });
Object.defineProperty(exports, "F7toD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toD55Adaptation; } });
Object.defineProperty(exports, "F7ToD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7ToD65Adaptation; } });
Object.defineProperty(exports, "F7toD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toD75Adaptation; } });
Object.defineProperty(exports, "F7toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toEAdaptation; } });
Object.defineProperty(exports, "F7toF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toF2Adaptation; } });
Object.defineProperty(exports, "F7toF11Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F7toF11Adaptation; } });
Object.defineProperty(exports, "F11toAAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toAAdaptation; } });
Object.defineProperty(exports, "F11toBAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toBAdaptation; } });
Object.defineProperty(exports, "F11toCAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toCAdaptation; } });
Object.defineProperty(exports, "F11toD50Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toD50Adaptation; } });
Object.defineProperty(exports, "F11toD55Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toD55Adaptation; } });
Object.defineProperty(exports, "F11ToD65Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11ToD65Adaptation; } });
Object.defineProperty(exports, "F11toD75Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toD75Adaptation; } });
Object.defineProperty(exports, "F11toEAdaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toEAdaptation; } });
Object.defineProperty(exports, "F11toF2Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toF2Adaptation; } });
Object.defineProperty(exports, "F11toF7Adaptation", { enumerable: true, get: function () { return chromatic_adaptation_1.F11toF7Adaptation; } });
var blender_1 = require("./utilities/blender");
Object.defineProperty(exports, "blend", { enumerable: true, get: function () { return blender_1.blend; } });
Object.defineProperty(exports, "Blender", { enumerable: true, get: function () { return blender_1.Blender; } });
var harmony_1 = require("./utilities/harmony");
Object.defineProperty(exports, "complementaryHarmony", { enumerable: true, get: function () { return harmony_1.complementaryHarmony; } });
Object.defineProperty(exports, "splitComplementaryHarmony", { enumerable: true, get: function () { return harmony_1.splitComplementaryHarmony; } });
Object.defineProperty(exports, "splitComplementaryCWHarmony", { enumerable: true, get: function () { return harmony_1.splitComplementaryCWHarmony; } });
Object.defineProperty(exports, "splitComplementaryCCWHarmony", { enumerable: true, get: function () { return harmony_1.splitComplementaryCCWHarmony; } });
Object.defineProperty(exports, "triadicHarmony", { enumerable: true, get: function () { return harmony_1.triadicHarmony; } });
Object.defineProperty(exports, "tetradicHarmony", { enumerable: true, get: function () { return harmony_1.tetradicHarmony; } });
Object.defineProperty(exports, "fourToneCWHarmony", { enumerable: true, get: function () { return harmony_1.fourToneCWHarmony; } });
Object.defineProperty(exports, "fourToneCCWHarmony", { enumerable: true, get: function () { return harmony_1.fourToneCCWHarmony; } });
Object.defineProperty(exports, "fiveToneAHarmony", { enumerable: true, get: function () { return harmony_1.fiveToneAHarmony; } });
Object.defineProperty(exports, "fiveToneBHarmony", { enumerable: true, get: function () { return harmony_1.fiveToneBHarmony; } });
Object.defineProperty(exports, "fiveToneCHarmony", { enumerable: true, get: function () { return harmony_1.fiveToneCHarmony; } });
Object.defineProperty(exports, "fiveToneDHarmony", { enumerable: true, get: function () { return harmony_1.fiveToneDHarmony; } });
Object.defineProperty(exports, "fiveToneEHarmony", { enumerable: true, get: function () { return harmony_1.fiveToneEHarmony; } });
Object.defineProperty(exports, "sixToneCWHarmony", { enumerable: true, get: function () { return harmony_1.sixToneCWHarmony; } });
Object.defineProperty(exports, "sixToneCCWHarmony", { enumerable: true, get: function () { return harmony_1.sixToneCCWHarmony; } });
Object.defineProperty(exports, "neutralHarmony", { enumerable: true, get: function () { return harmony_1.neutralHarmony; } });
Object.defineProperty(exports, "analogousHarmony", { enumerable: true, get: function () { return harmony_1.analogousHarmony; } });
Object.defineProperty(exports, "squareHarmony", { enumerable: true, get: function () { return harmony_1.squareHarmony; } });
var mixer_1 = require("./utilities/mixer");
Object.defineProperty(exports, "getShades", { enumerable: true, get: function () { return mixer_1.getShades; } });
Object.defineProperty(exports, "getTints", { enumerable: true, get: function () { return mixer_1.getTints; } });
Object.defineProperty(exports, "getTones", { enumerable: true, get: function () { return mixer_1.getTones; } });
var adapter_1 = require("./utilities/adapter");
Object.defineProperty(exports, "adapt", { enumerable: true, get: function () { return adapter_1.adapt; } });
Object.defineProperty(exports, "Adapter", { enumerable: true, get: function () { return adapter_1.Adapter; } });
var cie_delta_e_00_1 = require("./color-difference/cie-delta-e-00");
Object.defineProperty(exports, "deltaECIE00Lab", { enumerable: true, get: function () { return cie_delta_e_00_1.deltaECIE00Lab; } });
Object.defineProperty(exports, "deltaECIE00Rgb", { enumerable: true, get: function () { return cie_delta_e_00_1.deltaECIE00Rgb; } });
var cie_delta_e_76_1 = require("./color-difference/cie-delta-e-76");
Object.defineProperty(exports, "deltaECIE76Lab", { enumerable: true, get: function () { return cie_delta_e_76_1.deltaECIE76Lab; } });
Object.defineProperty(exports, "deltaECIE76Lch", { enumerable: true, get: function () { return cie_delta_e_76_1.deltaECIE76Lch; } });
Object.defineProperty(exports, "deltaECIE76Rgb", { enumerable: true, get: function () { return cie_delta_e_76_1.deltaECIE76Rgb; } });
var cie_delta_e_94_1 = require("./color-difference/cie-delta-e-94");
Object.defineProperty(exports, "deltaECIE94Lab", { enumerable: true, get: function () { return cie_delta_e_94_1.deltaECIE94Lab; } });
