import {
  sRgbToAdobeRgb,
  sRgbToAnsi16,
  sRgbToAnsi256,
  sRgbToAppleRgb,
  sRgbToBestRgb,
  sRgbToBetaRgb,
  sRgbToBruceRgb,
  sRgbToCieRgb,
  sRgbToCmy,
  sRgbToCmyk,
  sRgbToColorDonRgb4,
  sRgbToColorMatchRgb,
  sRgbToEciRgbV2,
  sRgbToEtkaSpacePs5,
  sRgbToHcy,
  sRgbToHex,
  sRgbToHsi,
  sRgbToHsl,
  sRgbToHsv,
  sRgbToHwb,
  sRgbToLab,
  sRgbToLch_ab,
  sRgbToLch_uv,
  sRgbToLuv,
  sRgbToNtscRgb,
  sRgbToPalSecamRgb,
  sRgbToProPhotoRgb,
  sRgbToRyb,
  sRgbToSmpteCRgb,
  sRgbToTsl,
  sRgbToWideGamutRgb,
  sRgbToXvYcc,
  sRgbToXyz,
  sRgbToYCbCrBT2020,
  sRgbToYCbCrBT601,
  sRgbToYCbCrBT709,
  sRgbToYCgCo,
  sRgbToYDbDr,
  sRgbToYPbPr,
  sRgbToYcCbcCrc,
  sRgbToYiq,
} from "../conversions/rgb-conversions";
import { RGBResolverMap } from "../interfaces/resolver.interface";

export const rgbResolverMap: RGBResolverMap = {
  adobe_98_rgb: sRgbToAdobeRgb,
  apple_rgb: sRgbToAppleRgb,
  ansi16: sRgbToAnsi16,
  ansi256: sRgbToAnsi256,
  best_rgb: sRgbToBestRgb,
  beta_rgb: sRgbToBetaRgb,
  bruce_rgb: sRgbToBruceRgb,
  cie_rgb: sRgbToCieRgb,
  color_match_rgb: sRgbToColorMatchRgb,
  cmy: sRgbToCmy,
  cmyk: sRgbToCmyk,
  don_rgb_4: sRgbToColorDonRgb4,
  etka_space_ps5: sRgbToEtkaSpacePs5,
  eci_rgb_v2: sRgbToEciRgbV2,
  hcy: sRgbToHcy,
  hex: sRgbToHex,
  hsi: sRgbToHsi,
  hsl: sRgbToHsl,
  hsv: sRgbToHsv,
  hwb: sRgbToHwb,
  lab: sRgbToLab,
  lch_ab: sRgbToLch_ab,
  lch_uv: sRgbToLch_uv,
  luv: sRgbToLuv,
  ntsc_rgb: sRgbToNtscRgb,
  pal_secam_rgb: sRgbToPalSecamRgb,
  pro_photo_rgb: sRgbToProPhotoRgb,
  ryb: sRgbToRyb,
  smpte_c_rgb: sRgbToSmpteCRgb,
  tsl: sRgbToTsl,
  wide_gamut_rgb: sRgbToWideGamutRgb,
  ycbcr_BT601: sRgbToYCbCrBT601,
  ycbcr_BT709: sRgbToYCbCrBT709,
  ycbcr_BT2020: sRgbToYCbCrBT2020,
  ydbdr: sRgbToYDbDr,
  ypbpr: sRgbToYPbPr,
  yccbccrc: sRgbToYcCbcCrc,
  ycgco: sRgbToYCgCo,
  yiq: sRgbToYiq,
  xvycc: sRgbToXvYcc,
  xyz: sRgbToXyz,
};
